import socket
import sys
sys.path.insert(0,"/home/ubuntu/python/program/ide")
from robosim import *

def main():
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	#s = serial.Serial("COM1", 9600)
	s.connect(('localhost', 55443))
	#Edit Block
	l = 40
	r = 40
	#End
	#End of Edit Block
	setSensor(s,"R",-45)



	setSensor(s,"L",-25)



	moveForward(s,30,150)

	while True:


		#Edit Block
		while readSensor(s,"IFR")<70: #Read Sensor
			#Edit Block
			l = l + 1
			r = r - 1
			#End of Edit Block
			setMotor(s,l,r)
		if readSensor(s,"IFL")<15: #Read Sensor
			#Edit Block
			l = l + 1
			r = r - 1
			#End of Edit Block
		elif readSensor(s,"IFL")<=30:
			#Edit Block
			l = 40
			r = 40
			#End of Edit Block
		else:
			#Edit Block
			l = l - 1
			r = r + 1
			#End of Edit Block
		setMotor(s,l,r)
		#En
		#End of Edit Block
	s.close()

if __name__ == "__main__":
	main()
	"""
Canvas generated by SPIRLe IDE
6	3
Item	of	Canvas	0	0
#Edit Block
	l = 40
	r = 40
	#End
	#End of Edit Block
Item	of	Canvas	1	0
setSensor(s,\"R\",-45)






Item	of	Canvas	2	0
setSensor(s,\"L\",-25)






Item	of	Canvas	3	0
moveForward(s,30,150)



Item	of	Canvas	4	0
while True:





Item	of	Canvas	4	1
#Edit Block
	while readSensor(s,\"IFR\")<70: #Read Sensor
		#Edit Block
		l = l + 1
		r = r - 1
		#End of Edit Block
		setMotor(s,l,r)
	if readSensor(s,\"IFL\")<15: #Read Sensor
		#Edit Block
		l = l + 1
		r = r - 1
		#End of Edit Block
	elif readSensor(s,\"IFL\")<=30:
		#Edit Block
		l = 40
		r = 40
		#End of Edit Block
	else:
		#Edit Block
		l = l - 1
		r = r + 1
		#End of Edit Block
	setMotor(s,l,r)
	#En
	#End of Edit Block
Item	of	Canvas	4	2
#End Conditional Block
This is the end of canvas"""