import socket
import sys
sys.path.insert(0,"/home/ubuntu/python/program/ide")
from robosim import *

def main():
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	#s = serial.Serial("COM1", 9600)
	s.connect(('localhost', 55443))
	while readSensor(s,"IFR")<70: #Read Sensor
		#Edit Block
		l = l + 1
		r = r - 1
		#End of Edit Block

		setMotor(s,l,r)

	if readSensor(s,"IFL")<15: #Read Sensor

		#Edit Block
		l = l + 1
		r = r - 1
		#End of Edit Block

	elif readSensor(s,"IFL")<=30:

		#Edit Block
		l = 40
		r = 40
		#End of Edit Block

	else:
		#Edit Block
		l = l - 1
		r = r + 1
		#End of Edit Block
	setMotor(s,l,r)
	s.close()

if __name__ == "__main__":
	main()
	"""
Canvas generated by SPIRLe IDE
6	4
Item	of	Canvas	0	0
while readSensor(s,\"IFR\")<70: #Read Sensor
Item	of	Canvas	0	1
#Edit Block
	l = l + 1
	r = r - 1
	#End of Edit Block


Item	of	Canvas	0	2
setMotor(s,l,r)


Item	of	Canvas	0	3
#End Conditional Block
Item	of	Canvas	1	0
if readSensor(s,\"IFL\")<15: #Read Sensor


Item	of	Canvas	1	1
#Edit Block
	l = l + 1
	r = r - 1
	#End of Edit Block


Item	of	Canvas	1	2
#End Conditional Block
Item	of	Canvas	2	0
elif readSensor(s,\"IFL\")<=30:


Item	of	Canvas	2	1
#Edit Block
	l = 40
	r = 40
	#End of Edit Block


Item	of	Canvas	2	2
#End Conditional Block
Item	of	Canvas	3	0
else:

Item	of	Canvas	3	1
#Edit Block
	l = l - 1
	r = r + 1
	#End of Edit Block

Item	of	Canvas	3	2
#End Conditional Block
Item	of	Canvas	4	0
setMotor(s,l,r)

This is the end of canvas"""